site_name: Apache Sedona&trade; (incubating) 
site_description: Apache Sedona&trade; (incubating) is a cluster computing system for processing large-scale spatial data. Sedona extends existing cluster computing systems, such as Apache Spark and Apache Flink, with a set of out-of-the-box distributed Spatial Datasets and Spatial SQL that efficiently load, process, and analyze large-scale spatial data across machines.
nav:
    - Home: index.md
    - Setup:
      - Overview: setup/overview.md
      - Supported platforms: 
        - Sedona with Apache Spark:
          - Modules: setup/modules.md
          - Language wrappers: setup/platform.md
        - Sedona with Apache Flink:
          - Modules: setup/flink/modules.md
          - Language wrappers: setup/flink/platform.md
      - Maven Central coordinate: setup/maven-coordinates.md
      - Install with Apache Spark:
        - Install Sedona Scala/Java: setup/install-scala.md
        - Install Sedona Python: setup/install-python.md
        - Install Sedona R: setup/install-r.md
        - Install Sedona-Zeppelin: setup/zeppelin.md
        - Install on Databricks: setup/databricks.md
        - Set up Spark cluser: setup/cluster.md
      - Install with Apache Flink:
        - Install Sedona Scala/Java: setup/flink/install-scala.md
      - Release notes: setup/release-notes.md      
      - Compile the code: setup/compile.md
    - Download: download.md
    - Programming Guides:
      - Sedona with Apache Spark:
        - Spatial SQL app:
          - Scala/Java: tutorial/sql.md
          - Pure SQL: tutorial/sql-pure-sql.md
          - Python: tutorial/sql-python.md
          - R: tutorial/sql-r.md
          - Raster data - Map Algebra: tutorial/raster.md      
        - Spatial RDD app:
          - Scala/Java: tutorial/rdd.md
          - Python: tutorial/core-python.md
          - R: tutorial/rdd-r.md
        - Map visualization SQL app:
          - Scala/Java: tutorial/viz.md
          - Use Apache Zeppelin: tutorial/zeppelin.md
          - R: tutorial/viz-r.md
          - Gallery: tutorial/viz-gallery.md
        - Performance tuning:
          - Benchmark: tutorial/benchmark.md            
          - Tune RDD application: tutorial/Advanced-Tutorial-Tune-your-Application.md
      - Sedona with Apache Flink:
        - Spatial SQL app:
          - Scala/Java: tutorial/flink/sql.md
      - Examples:
          - Scala/Java: tutorial/demo.md
          - Python: tutorial/jupyter-notebook.md
    - API Docs:
      - Sedona with Apache Spark:
        - SQL:
          - Quick start: api/sql/Overview.md
          - Vector data:
              - Constructor: api/sql/Constructor.md
              - Function: api/sql/Function.md
              - Predicate: api/sql/Predicate.md
              - Aggregate function: api/sql/AggregateFunction.md
              - Join query (optimizer): api/sql/Optimizer.md
          - Raster data:
              - Raster input and output: api/sql/Raster-loader.md
              - Raster operators: api/sql/Raster-operators.md
          - Parameter: api/sql/Parameter.md
        - RDD (core):
          - Scala/Java doc: api/java-api.md
          - Python doc: api/python-api.md
          - R doc: api/r-api.md
        - Viz:
          - DataFrame/SQL: api/viz/sql.md
          - RDD: api/viz/java-api.md
      - Sedona with Apache Flink:
        - SQL:
          - Overview: api/flink/Overview.md
          - Constructor: api/flink/Constructor.md
          - Function: api/flink/Function.md
          - Aggregator: api/flink/Aggregator.md
          - Predicate: api/flink/Predicate.md
    - Community:
      - Community: community/contact.md 
      - Contributor Guide:
        - Rules: community/rule.md
        - Develop: community/develop.md
      - Committer Guide:
        - Project Management Committee: community/contributor.md
        - Become a release manager: community/release-manager.md
        - Publish a snapshot version: community/snapshot.md
        - Make a release: community/publish.md
        - Vote a release: community/vote.md
      - Publications: community/publication.md
    - GeoSpark Legacy Docs:
      - Download:
        - Quick start: archive/download/overview.md
        - Release notes: archive/download/GeoSpark-All-Modules-Release-notes.md      
        - Maven Central coordinate: archive/download/GeoSpark-All-Modules-Maven-Central-Coordinates.md
        - Set up Spark cluser: archive/download/cluster.md
        - Spark Scala shell: archive/download/scalashell.md
        - Self-contained project: archive/download/project.md
        - Install GeoSpark-Zeppelin: archive/download/zeppelin.md
        - Compile the source code: archive/download/compile.md
      - Tutorial:
        - Spatial RDD application: archive/tutorial/rdd.md
        - Spatial SQL application: archive/tutorial/sql.md
        - Visualize Spatial DataFrame: archive/tutorial/viz.md
        - Run GeoSpark via Zeppelin: archive/tutorial/zeppelin.md
        - Spatial RDD in Python: archive/tutorial/geospark-core-python.md
        - Spatial SQL in Python: archive/tutorial/geospark-sql-python.md
        - GeoSpark template project: archive/tutorial/GeoSpark-Runnable-DEMO.md
        - Frequently Asked Questions: archive/tutorial/faq.md
        - Tune GeoSpark RDD application: archive/tutorial/Advanced-Tutorial-Tune-your-GeoSpark-Application.md
        - Benchmark: archive/tutorial/benchmark.md
      - API:
        - GeoSpark core (RDD):
          - Scala/Java doc: archive/api/GeoSpark-Scala-and-Java-API.md
          - Python doc: archive/api/GeoSpark-Python-API.md
        - GeoSpark SQL:
          - JavaDoc: archive/api/sql/GeoSparkSQL-javadoc.md
          - Quick start: archive/api/sql/GeoSparkSQL-Overview.md
          - Constructor: archive/api/sql/GeoSparkSQL-Constructor.md
          - Function: archive/api/sql/GeoSparkSQL-Function.md
          - Predicate: archive/api/sql/GeoSparkSQL-Predicate.md
          - Aggregate function: archive/api/sql/GeoSparkSQL-AggregateFunction.md
          - Join query (optimizer): archive/api/sql/GeoSparkSQL-Optimizer.md
          - Parameter: archive/api/sql/GeoSparkSQL-Parameter.md
        - GeoSpark Viz:
          - DataFrame/SQL: archive/api/viz/sql.md
          - RDD: archive/api/viz/Babylon-Scala-and-Java-API.md
    - Apache Software Foundation:
      - Foundation: asf/asf.md
      - Disclaimer: asf/disclaimer.md
      - License: https://www.apache.org/licenses/" target="_blank
      - Events: https://www.apache.org/events/current-event" target="_blank
      - Sponsorship: https://www.apache.org/foundation/sponsorship.html" target="_blank
      - Thanks: https://www.apache.org/foundation/thanks.html" target="_blank
      - Security: https://www.apache.org/security/" target="_blank
      - Privacy: https://privacy.apache.org/policies/privacy-policy-public.html" target="_blank
repo_url: https://github.com/apache/incubator-sedona
repo_name: apache/incubator-sedona
theme:
  font: false
  name: 'material'
  custom_dir: docs-overrides
  palette:
    primary: 'deep orange'
    accent: 'green'
  favicon: https://www.apache.org/logos/res/sedona/sedona.png
  icon:
    logo: fontawesome/solid/earth-americas
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/apache/incubator-sedona'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/ApacheSedona'
  sedona:
    current_version: 1.3.0-incubating
    current_geotools: 1.3.0-27.2
  sedona_create_release:
    current_version: 1.3.1-incubating
    current_git_tag: sedona-1.3.1-incubating-rc1
    current_rc: 1.3.1-incubating-rc1
    current_snapshot: 1.3.1-incubating-SNAPSHOT
copyright: Copyright © 2022 The Apache Software Foundation
markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
plugins:
  - search:
      prebuild_index: true
  - macros
  - git-revision-date-localized:
      type: datetime
